spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bsm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis:
  type-aliases-package: com.szxs.pojo
  mapper-locations: classpath:xml/*.xml
server:
  port: 8080